### ISSUE TITLE
Make using `resume` on a different day work sensibly

### ISSUE THREAD

**Issue by aisopuro** [hegenator/ots#6]
The current behaviour is for `ots resume` to move the timesheet entry being resumed to the current day.

It should instead start a new entry with the same details if the timesheet being resumed is on a different day.

So if you had an entry like
```
x.y    T1234    Handle parsing errors when importing XML    03:42
```
yesterday (or last week, or last year), when you called `ots resume x.y` you would start a new entry like
```
0    T1234    Handle parsing errors when importing XML    00:00
```

**Comment by aisopuro** [comment]
I am currently working on this. :pushpin:

**Comment by hegenator** [comment]
Yes, would be a very nice improvement 👍
