### ISSUE TITLE
Probably bug: resuming timesheets from different days keeps them linked to Odoo

### ISSUE THREAD

**Issue by aisopuro** [hegenator/ots#9]
The latest `resume` changes do not reset the `odoo_id` field on copied timesheets. This likely leads to the new copy being linked to the same timesheet record in Odoo, even though that is not what is wanted.

The call to `copy` should unset `odoo_id` so that the new copy is not linked to the Odoo record.

Possibly `copy` should always do this?

It would be cool to add tests for this, but they would require mocking, is that hard?

**Comment by aisopuro** [comment]
Actually might not be a problem because the constructor doesn't take `odoo_id`, so `copy` doesn't use it.

**Comment by hegenator** [comment]
Confirmed not a problem, copying does not copy the odoo_id. Closing
